### ISSUE TITLE
Charlie Integration

### ISSUE THREAD

**Issue by randyhart** [18F/procurement-glossary#8]
When I used slack/Charlie commands for common CO slang like "charlie define D&F" and "charlie define protest" I got back a response of "I don't know that term".

I don't know whether this is a "charlie" issue or a "glossary" issue but wanted to flag it for correction.

**Comment by mgwalker** [comment]
The regex Charlie uses to find terms to lookup only finds the first word, up to a regex "word" character (so, e.g., "D&F" only matches "D").

https://github.com/18F/18f-bot/blob/master/scripts/glossary.coffee#L23

Using `(.+)` instead of `(\w+)` should take care of it.  Should this be crossposted to https://github.com/18F/18f-bot?

**Comment by stvnrlly** [comment]
I'd say to skip the issue in that repo and just submit a PR over there. Using `(.+)` would be good for multiple word phrases, but if we're not expecting that then `(\S+)` is another option that should work.

**Comment by randyhart** [comment]
did i just screw something up?  I'm completely out of my element.

**Comment by stvnrlly** [comment]
Ha, no, everything is :+1:. It looks like you identified two separate issues: 
1. The charlie command doesn't pick up "D&F", which is in the glossary.
2. A common term like "protest" is not in the glossary and should be.

For the first issue, the fix would be over in the charlie repo, and can be fixed by changing the regular expression that charlie is using to figure out what term you ask to define. Regular expressions are kind of crazy, but essentially are ways of writing a pattern to figure out whether a sentence or something includes a specific set of characters. The regular expression code of `\w` only matches a "word" character (basically a letter or number), so it doesn't match "D&F" because of the & symbol. The `.` code that @mgwalker is proposing would match _any_ character, so it would pick up on "D&F".

For the second issue, we should add "protest" to the glossary. I think that's something that you could do, and it can be done entirely within GitHub. I'm happy to show you how.
